# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(458, 435)
        MainWindow.setMaximumSize(QtCore.QSize(458, 450))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: \"#f0f1f4\"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_operant = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_operant.sizePolicy().hasHeightForWidth())
        self.label_operant.setSizePolicy(sizePolicy)
        self.label_operant.setMinimumSize(QtCore.QSize(30, 0))
        self.label_operant.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_operant.setFont(font)
        self.label_operant.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_operant.setAlignment(QtCore.Qt.AlignCenter)
        self.label_operant.setObjectName("label_operant")
        self.verticalLayout.addWidget(self.label_operant)
        self.label_memory = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_memory.sizePolicy().hasHeightForWidth())
        self.label_memory.setSizePolicy(sizePolicy)
        self.label_memory.setMinimumSize(QtCore.QSize(30, 0))
        self.label_memory.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_memory.setFont(font)
        self.label_memory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_memory.setObjectName("label_memory")
        self.verticalLayout.addWidget(self.label_memory)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(400, 80))
        self.lcdNumber.setMaximumSize(QtCore.QSize(600, 100))
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_ac = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ac.setEnabled(True)
        self.btn_ac.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ac.setFont(font)
        self.btn_ac.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_ac.setStyleSheet("color:rgb(255, 0, 0);\n"
"background:\"#fbc11a\"\n"
"")
        self.btn_ac.setObjectName("btn_ac")
        self.gridLayout.addWidget(self.btn_ac, 0, 0, 1, 1)
        self.btn_m = QtWidgets.QPushButton(self.centralwidget)
        self.btn_m.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_m.setFont(font)
        self.btn_m.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"    background:#eae7e0\n"
"}")
        self.btn_m.setObjectName("btn_m")
        self.gridLayout.addWidget(self.btn_m, 0, 1, 1, 1)
        self.btn_mr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mr.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mr.setFont(font)
        self.btn_mr.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"    background:\"#eae7e0\";\n"
"}")
        self.btn_mr.setObjectName("btn_mr")
        self.gridLayout.addWidget(self.btn_mr, 0, 2, 1, 1)
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.gridLayout.addWidget(self.btn_div, 0, 3, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 1, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setAutoFillBackground(False)
        self.btn8.setStyleSheet("color:\"#1976D2\";\n"
"")
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 1, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 1, 2, 1, 1)
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mult.setFont(font)
        self.btn_mult.setObjectName("btn_mult")
        self.gridLayout.addWidget(self.btn_mult, 1, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 2, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 2, 1, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 2, 2, 1, 1)
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sub.setFont(font)
        self.btn_sub.setObjectName("btn_sub")
        self.gridLayout.addWidget(self.btn_sub, 2, 3, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 3, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 3, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 3, 2, 1, 1)
        self.btn_sum = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sum.sizePolicy().hasHeightForWidth())
        self.btn_sum.setSizePolicy(sizePolicy)
        self.btn_sum.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sum.setFont(font)
        self.btn_sum.setObjectName("btn_sum")
        self.gridLayout.addWidget(self.btn_sum, 3, 3, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 4, 0, 1, 1)
        self.btn_pro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pro.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pro.setFont(font)
        self.btn_pro.setObjectName("btn_pro")
        self.gridLayout.addWidget(self.btn_pro, 4, 1, 1, 1)
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("QPushButton {\n"
"color: #4CAF50;\n"
"}")
        self.btn_equal.setObjectName("btn_equal")
        self.gridLayout.addWidget(self.btn_equal, 4, 2, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionkkk = QtWidgets.QAction(MainWindow)
        self.actionkkk.setObjectName("actionkkk")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label_operant.setText(_translate("MainWindow", "O"))
        self.label_memory.setText(_translate("MainWindow", "M"))
        self.btn_ac.setText(_translate("MainWindow", "AC"))
        self.btn_ac.setShortcut(_translate("MainWindow", "Backspace"))
        self.btn_m.setText(_translate("MainWindow", "M"))
        self.btn_m.setShortcut(_translate("MainWindow", "M"))
        self.btn_mr.setText(_translate("MainWindow", "MR"))
        self.btn_mr.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_div.setShortcut(_translate("MainWindow", "/"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn7.setShortcut(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn8.setShortcut(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn9.setShortcut(_translate("MainWindow", "9"))
        self.btn_mult.setText(_translate("MainWindow", "x"))
        self.btn_mult.setShortcut(_translate("MainWindow", "*"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn5.setShortcut(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn6.setShortcut(_translate("MainWindow", "6"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_sub.setShortcut(_translate("MainWindow", "-"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn2.setShortcut(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn3.setShortcut(_translate("MainWindow", "3"))
        self.btn_sum.setText(_translate("MainWindow", "+"))
        self.btn_sum.setShortcut(_translate("MainWindow", "+"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn0.setShortcut(_translate("MainWindow", "0"))
        self.btn_pro.setText(_translate("MainWindow", "%"))
        self.btn_pro.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_equal.setShortcut(_translate("MainWindow", "="))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionkkk.setText(_translate("MainWindow", "kkk"))
